server:
  port: 8081

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:payment
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always